filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: false
tools:
    external_code_coverage:
        timeout: 600
